### ISSUE TITLE
Staking is not working properly in the latest version, it does not show the real amount of coins.

### ISSUE THREAD

**Issue by olgyan93btc** [zcomputerwiz/silicoin-blockchain#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by olgyan93btc** [comment]
11111

**Comment by zcomputerwiz** [comment]
> 11111

Is this for Gold Blockchain?
